name: Publish Nuget Packages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      env: # Or as an environment variable
        INTERVAL_CRON_GENERATOR_KEY: ${{ secrets.INTERVAL_CRON_GENERATOR_KEY }}
    - name: Build and Publish
      run: bash ./publish.sh
      env: # Or as an environment variable
        INTERVAL_CRON_GENERATOR_KEY: ${{ secrets.INTERVAL_CRON_GENERATOR_KEY }}
